from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registro/', views.register, name='register'),
    path('registro/voluntario/', views.register_volunteer, name='register_volunteer'),
    path('registro/instituicao/', views.register_institution, name='register_institution'),
    path('dashboard/voluntario/', views.volunteer_dashboard, name='volunteer_dashboard'),
    path('dashboard/voluntario/perfil/', views.volunteer_profile, name='volunteer_profile'),
    path('dashboard/voluntario/inscricoes/', views.volunteer_registrations, name='volunteer_registrations'),
    path('dashboard/voluntario/historico/', views.volunteer_history, name='volunteer_history'),
    path('dashboard/instituicao/', views.institution_dashboard, name='institution_dashboard'),
    path('dashboard/instituicao/perfil/', views.institution_profile, name='institution_profile'),
    path('dashboard/instituicao/oportunidades/nova/', views.criar_oportunidade, name='criar_oportunidade'),
    path('dashboard/instituicao/oportunidades/<int:id>/editar/', views.editar_oportunidade, name='editar_oportunidade'),
    path('dashboard/instituicao/oportunidades/<int:id>/apagar/', views.apagar_oportunidade, name='apagar_oportunidade'),
    path('dashboard/instituicao/oportunidades/<int:id>/inscricoes/', views.gerir_inscricoes, name='gerir_inscricoes'),
    path('dashboard/instituicao/oportunidades/<int:id>/inscricoes/exportar/', views.exportar_inscricoes, name='exportar_inscricoes'),
    path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/admin/utilizadores/', views.admin_users, name='admin_users'),
    path('dashboard/admin/instituicoes/', views.admin_institutions, name='admin_institutions'),
    path('dashboard/admin/categorias/', views.admin_categories, name='admin_categories'),
    path('dashboard/admin/relatorios/', views.admin_reports, name='admin_reports'),
    path('dashboard/admin/oportunidades/', views.admin_oportunidades, name='admin_oportunidades'),
    path('dashboard/admin/oportunidades/<int:id>/', views.admin_aprovar_oportunidade, name='admin_aprovar_oportunidade'),
    path('password-reset/', views.password_reset, name='password_reset'),
    path('notificacoes/', views.notificacoes, name='notificacoes'),
    path('notificacoes/<int:id>/ler/', views.marcar_notificacao_lida, name='marcar_notificacao_lida'),
    path('notificacoes/todas-lidas/', views.marcar_todas_lidas, name='marcar_todas_lidas'),
    path('certificados/<int:oportunidade_id>/gerar/', views.gerar_certificado, name='gerar_certificado'),
    path('certificados/<int:oportunidade_id>/download/', views.download_certificado, name='download_certificado'),
    path('relatorio-pdf/', views.relatorio_pdf, name='relatorio_pdf'),
    path('avaliar/<int:oportunidade_id>/', views.avaliar_oportunidade, name='avaliar_oportunidade'),
    path('dashboard/admin/tags/', views.gerir_tags, name='gerir_tags'),
    path('dashboard/voluntario/tags/', views.voluntario_tags, name='voluntario_tags'),
]
