# Generated by Django 6.0.7 on 2026-07-13 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('freguesia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=200, null=True)),
                ('vagas', models.IntegerField(default=1)),
                ('requisitos', models.TextField(blank=True, null=True)),
                ('idade_minima', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberta', 'Aberta'), ('publicada', 'Publicada'), ('inscricoes_encerradas', 'Inscrições Encerradas'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=25)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='oportunidades.categoria')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='accounts.institution')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('submetida', 'Submetida'), ('aceite', 'Aceite'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='submetida', max_length=20)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('data_decisao', models.DateTimeField(blank=True, null=True)),
                ('observacoes_instituicao', models.TextField(blank=True, null=True)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='oportunidades.oportunidade')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('oportunidade', 'voluntario')},
            },
        ),
    ]
