# Generated by Django 6.0.7 on 2026-07-14 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='estado',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente de Aprovação'), ('aberta', 'Aberta'), ('publicada', 'Publicada'), ('inscricoes_encerradas', 'Inscrições Encerradas'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=25),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='oportunidades.oportunidade')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'unique_together': {('voluntario', 'oportunidade')},
            },
        ),
    ]
