# Generated by Django 6.0.7 on 2026-07-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tag_volunteertag'),
        ('oportunidades', '0002_alter_oportunidade_estado_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='oportunidades', to='accounts.tag'),
        ),
    ]
