# Generated by Django 6.0.7 on 2026-07-13 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('entidade', models.CharField(max_length=100)),
                ('entidade_id', models.CharField(blank=True, max_length=100, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('detalhe', models.TextField(blank=True, null=True)),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de Atividade',
                'verbose_name_plural': 'Registos de Atividades',
                'ordering': ['-data_hora'],
            },
        ),
    ]
