# Generated by Django 6.0.7 on 2026-07-14 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('oportunidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('inscricao_recebida', 'Inscrição Recebida'), ('inscricao_aceite', 'Inscrição Aceite'), ('inscricao_recusada', 'Inscrição Recusada'), ('inscricao_concluida', 'Inscrição Concluída'), ('nova_oportunidade', 'Nova Oportunidade'), ('oportunidade_atualizada', 'Oportunidade Atualizada'), ('instituicao_aprovada', 'Instituição Aprovada'), ('instituicao_recusada', 'Instituição Recusada'), ('sistema', 'Notificação do Sistema')], default='sistema', max_length=30)),
                ('lida', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao_nome', models.CharField(max_length=200)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('horas_voluntariado', models.IntegerField(default=0)),
                ('descricao_atividade', models.TextField(blank=True, null=True)),
                ('codigo_verificacao', models.CharField(max_length=50, unique=True)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='oportunidades.oportunidade')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'unique_together': {('voluntario', 'oportunidade')},
            },
        ),
    ]
