# Generated by Django 6.0.7 on 2026-07-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_volunteer_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cor', models.CharField(default='#0d6efd', max_length=7)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermédio'), (3, 'Avançado')], default=1)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='accounts.tag')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.volunteer')),
            ],
            options={
                'verbose_name': 'Tag de Voluntário',
                'verbose_name_plural': 'Tags de Voluntários',
                'unique_together': {('voluntario', 'tag')},
            },
        ),
    ]
